language: ruby
rvm:
  - 1.9.3
  - 2.1.1
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
services:
  - redis-server
notifications:
  irc:
    channels: 
      - "chat.freenode.net#websocket-rails"
    on_success: change
